"""add_bar_type_and_owner_id

Revision ID: b1943b103d92
Revises: 0002_search_vector_trigger
Create Date: 2026-03-17 14:42:45.034770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1943b103d92'
down_revision: Union[str, Sequence[str], None] = '0002_search_vector_trigger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_user_memberships',
    sa.Column('bar_id', sa.String(length=21), nullable=False),
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('bar_id', 'user_id', name='pk_bar_user_memberships')
    )
    op.drop_index(op.f('ix_activity_log_created_at'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_target'), table_name='activity_log')
    op.add_column('agents', sa.Column('owner_id', sa.String(length=21), nullable=True))
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'users', ['owner_id'], ['id'])
    op.add_column('bar_invites', sa.Column('target_user_id', sa.String(length=21), nullable=True))
    op.drop_index(op.f('ix_bar_invites_created_by'), table_name='bar_invites')
    op.drop_constraint(op.f('bar_invites_target_agent_id_fkey'), 'bar_invites', type_='foreignkey')
    op.create_foreign_key(None, 'bar_invites', 'users', ['target_user_id'], ['id'])
    op.drop_column('bar_invites', 'target_agent_id')
    op.drop_index(op.f('ix_bar_memberships_agent_id'), table_name='bar_memberships')
    op.add_column('bars', sa.Column('bar_type', sa.String(length=20), server_default='public', nullable=False))
    op.create_index(op.f('ix_bars_bar_type'), 'bars', ['bar_type'], unique=False)
    op.create_index(op.f('ix_bars_join_mode'), 'bars', ['join_mode'], unique=False)
    op.drop_index(op.f('ix_posts_bar_entity'), table_name='posts')
    op.drop_index(op.f('ix_posts_bar_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_search_vector'), table_name='posts', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_search_vector'), 'posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_posts_bar_status'), 'posts', ['bar_id', 'status'], unique=False)
    op.create_index(op.f('ix_posts_bar_entity'), 'posts', ['bar_id', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_bars_join_mode'), table_name='bars')
    op.drop_index(op.f('ix_bars_bar_type'), table_name='bars')
    op.drop_column('bars', 'bar_type')
    op.create_index(op.f('ix_bar_memberships_agent_id'), 'bar_memberships', ['agent_id'], unique=False)
    op.add_column('bar_invites', sa.Column('target_agent_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bar_invites', type_='foreignkey')
    op.create_foreign_key(op.f('bar_invites_target_agent_id_fkey'), 'bar_invites', 'agents', ['target_agent_id'], ['id'])
    op.create_index(op.f('ix_bar_invites_created_by'), 'bar_invites', ['created_by'], unique=False)
    op.drop_column('bar_invites', 'target_user_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.drop_column('agents', 'owner_id')
    op.create_index(op.f('ix_activity_log_target'), 'activity_log', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_activity_log_created_at'), 'activity_log', ['created_at'], unique=False)
    op.drop_table('bar_user_memberships')
    # ### end Alembic commands ###
